HMS/HMS/urls.py
from django.contrib import admin
from django.urls import path
from hospital import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('department_user_view/', views.department_user_view, name='department_user_view'),
    path('doctor_user_view/', views.doctor_user_view, name='doctor_user_view'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('cancel/signup/<int:user_profile_id>/', views.cancel_signup, name='cancel_signup'),
    path('success/', views.signup_success_view, name='success'),
    path('logout/', views.user_logout, name='logout'),

    #Admin
    path('custom_admin_dashboard/', views.custom_admin_dashboard, name='custom_admin_dashboard'),
    path('edit-admin-profile/', views.update_admin_profile, name='edit_admin_profile'), 

    path('custom_admin_dashboard/create_admission/', views.create_admission, name='create_admission'),
    path('view_admissions/', views.view_admissions, name='view_admissions'),
    path('admissions/<int:admission_id>/edit/', views.update_admission, name='edit_admission'),
    path('admissions/<int:admission_id>/delete/', views.delete_admission, name='delete_admission'),
    path('discharged_patients/', views.view_discharged_patients, name='view_discharged_patients'),

    path('create_department/', views.create_department, name='create_department'),
    path('view_departments/', views.view_departments, name='view_departments'),
    path('departments/<int:department_id>/edit/', views.update_department, name='edit_department'),
    path('departments/<int:department_id>/delete/', views.delete_department, name='delete_department'),

    path('ward/create/', views.create_ward, name='create_ward'),
    path('ward/list/', views.view_wards, name='view_wards'),
    path('wards/<int:ward_id>/edit/', views.update_ward, name='edit_ward'),
    path('wards/<int:ward_id>/delete/', views.delete_ward, name='delete_ward'),

    path('shifts/create/', views.create_shift, name='create_shift'),
    path('shift/list/', views.view_shifts, name='view_shifts'),
    path('shifts/<int:shift_id>/edit/', views.update_shift, name='edit_shift'),
    path('shifts/<int:shift_id>/delete/', views.delete_shift, name='delete_shift'),
    
    path('create_billing/', views.create_billing, name='create_billing'),
    path('view_billings/', views.view_billings, name='view_billings'),
    path('billings/<int:billing_id>/delete/', views.delete_billing, name='delete_billing'),
    path('billings/<int:billing_id>/edit/', views.update_billing, name='edit_billing'),
    
    path('create_bed/', views.create_bed, name='create_bed'),
    path('beds/', views.view_beds, name='view_beds'),
    path('beds/<int:bed_id>/edit/', views.update_bed, name='edit_bed'),
    path('beds/<int:bed_id>/delete/', views.delete_bed, name='delete_bed'),
    
    path('view-patients/', views.view_patients, name='view_patients'),
    path('create-patient/', views.create_patient, name='create_patient'),
    path('edit-patient/<int:patient_id>/', views.update_patient, name='edit_patient'),
    path('delete-patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    
    path('create_doctor/', views.create_doctor, name='create_doctor'),
    path('view_doctors/', views.view_doctors, name='view_doctors'),
    path('edit-doctor/<int:doctor_id>/', views.update_doctor, name='edit_doctor'),
    path('delete-doctor/<int:doctor_id>/', views.delete_doctor, name='delete_doctor'),

    path('create_user/', views.create_user, name='create_user'),
    path('view_users/', views.view_users, name='view_users'),
    path('edit_user/<int:user_id>/', views.update_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),

    path('doctor-nurse-requests/', views.doctor_nurse_requests, name='doctor_nurse_requests'),
    path('approve-account/<int:user_id>/', views.approve_account, name='approve_account'),
    path('reject-account/<int:user_id>/', views.reject_account, name='reject_account'),
    
    #PatientProfile
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient_signup/<int:user_profile_id>/', views.patient_signup_view, name='patient_signup'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('appointment_view/<int:doctorID>/', views.appointment_view, name='appointment_view'),

    #DoctorProfile
    path('doctor/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctor_signup/<int:user_profile_id>/', views.doctor_signup_view, name='doctor_signup'),
    path('appointments/', views.appointment_list, name='appointment_list'),
    path('appointments/accept/<int:appointment_id>/', views.accept_appointment, name='accept_appointment'),
]   

HMS/hospital/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from datetime import date

class UserProfile(AbstractUser):
    email = models.EmailField(unique=True)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.CharField(max_length=200)
    date_of_birth = models.DateField(default=date.today)
    contact_no = models.IntegerField(
        validators=[
            MinValueValidator(1500000000),  
            MaxValueValidator(1999999999)
        ], unique=True, default=0000000000
    )
    ACCOUNT_TYPE_CHOICES = [
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
    ]
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPE_CHOICES, blank=False, null=False)
    is_approved = models.BooleanField(default=True)
    
    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.username}" 
    
class Department(models.Model):
    DEPARTMENT_CHOICES = [
        ('cardiology', 'Cardiology'),
        ('neurology', 'Neurology'),
        ('orthopedics', 'Orthopedics'),
        ('pediatrics', 'Pediatrics')
    ]

    name = models.CharField(max_length=100, unique=True, choices=DEPARTMENT_CHOICES)
    description = models.TextField()
    head_doctor = models.OneToOneField('DoctorProfile', related_name='head_of_department', unique=True, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.get_name_display()} Department"

class Shift(models.Model):
    SHIFT_CHOICES = [
        ('day', 'Day Shift'),
        ('evening', 'Evening Shift'),
        ('night', 'Night Shift')
    ]

    type = models.CharField(max_length=20, unique=True, choices=SHIFT_CHOICES)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"{self.get_type_display()} - {self.start_time} to {self.end_time}"


class DoctorProfile(models.Model):
    user_profile = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    specialization = models.CharField(max_length=100)
    qualifications = models.TextField()
    
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    shift = models.ForeignKey(Shift, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return f"{self.user_profile.first_name} {self.user_profile.last_name}"
    

class PatientProfile(models.Model):
    user_profile = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    medical_history = models.TextField()
    prescribed_medications = models.TextField()


    def __str__(self):
        return self.user_profile.username 

    
class Appointment(models.Model):
    STATUS_CHOICES = [
        ('scheduled', 'Scheduled'),
        ('confirmed', 'Confirmed'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
        ('no_show', 'No Show'),
        ('rescheduled', 'Rescheduled'),
        ('pending', 'Pending'),
    ]
    date = models.DateField()
    time = models.TimeField()
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='scheduled')
    problem = models.TextField()
    accepted = models.BooleanField(default=False)
    
    def __str__(self):
        return f"Appointment on {self.date} at {self.time} with Dr. {self.doctor} for {self.patient}: {self.get_status_display()}"

class Billing(models.Model):

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('paid', 'Paid'),
    ]

    PAYMENT_METHOD_CHOICES = [
        ('cash', 'Cash'),
        ('online', 'Online')
    ]

    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES)

    def __str__(self):
        return f"Billing for {self.patient} - Total Amount: {self.total_amount}, Status: {self.status}"

class Ward(models.Model): 
    WARD_TYPES = [
        ('general', 'General Ward'),
        ('specialized', 'Specialized Ward'),
        ('isolation', 'Isolation Ward'),
        ('hdu', 'High Dependency Unit (HDU)'),
        ('private', 'Private Ward')
    ]

    name = models.CharField(
        max_length=1,
        unique=True,
        validators=[
            RegexValidator(
                regex='^[A-Z]$',  
                message='Ward name should be a single letter from A to Z.',
                code='invalid_ward_name'
            )
        ]
    )
    ward_type = models.CharField(max_length=50,  choices=WARD_TYPES)
    
    @property
    def capacity(self):
        return self.bed_set.count()

    @property
    def occupancy(self):
        return Admission.objects.filter(bed__ward=self).count()

    def __str__(self):
        return f"{self.name} ({self.get_ward_type_display()})"
    
class Bed(models.Model):

    ward = models.ForeignKey(Ward, on_delete=models.CASCADE)
    bed_number = models.IntegerField()
    class Meta:
        unique_together = ('ward', 'bed_number')
    
    @property
    def bed_name(self):
        return f'{self.ward.name}{self.bed_number}'
    def __str__(self):
        return f"{self.ward.name}{self.bed_number}({self.ward.ward_type})"
    
class Admission(models.Model):
    patient = models.OneToOneField(PatientProfile, on_delete=models.CASCADE)
    bed = models.OneToOneField(Bed, on_delete=models.CASCADE)
    admission_datetime = models.DateTimeField()

    def __str__(self):
        return f"Admission for {self.patient} in {self.ward}"
    
class DischargedPatient(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    bed_name = models.CharField(max_length=100)
    admission_datetime = models.DateTimeField()
    discharge_datetime = models.DateTimeField()

    def __str__(self):
        return f"Discharged Patient: {self.patient.user_profile.full_name}"

HMS/hospital/templates/appointment_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appointment List</title>
    <link rel="stylesheet" href="{% static 'css/view_admissions.css' %}">
</head>
<body>
    <h1>Appointment List</h1>
    <table>
        <thead>
            <tr>
                <th>Patient Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for appointment in appointments %}
            <tr>
                <td>{{ appointment.patient.user_profile.username }}</td>
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>
                <td>{% if appointment.accepted %}Accepted{% else %}Pending{% endif %}</td>
                <td><a href="{% url 'accept_appointment' appointment.id %}">Accept</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

HMS/hospital/templates/create_billing.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Billing</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Create Billing</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Billing">
        <a href="{% url 'view_billings' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/create_department.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Department</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Create Department</h1>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Department">
        <a href="{% url 'view_departments' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/create_patient.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Patient</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Create Patient Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
        <a href="{% url 'view_patients' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/create_ward.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Ward</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Create Ward</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Ward">
        <a href="{% url 'view_wards' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/delete_confirmation.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
    <link rel="stylesheet" href="{% static 'css/delete_confirmation.css' %}">
</head>
<body>
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete ?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'custom_admin_dashboard' %}">Cancel</a>
    </form>
</body>
</html>

HMS/hospital/templates/doctor_dashboard.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Doctor Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/doctor_dashboard.css' %}">
</head>
<body>
    <header>
    </header>

    <main>
        <section>
            <h2>Welcome, {{ doctor.user_profile.username }}</h2>
            <p>Doctor's Details:</p>
            <ul>
                <li>Name: {{ doctor.user_profile.first_name }} {{ doctor.user_profile.last_name }}</li>
                <li>Email: {{ doctor.user_profile.email }}</li>
                <li>Specialization: {{ doctor.specialization }}</li>
            </ul>
        </section>

        <section>
            <a href="{% url 'appointment_list' %}">Appointment List</a>
        </section>
    </main>
    <a href="{% url 'logout' %}">Logout</a>
    <footer>
    </footer>
    
</body>
</html>

HMS/hospital/templates/signup.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Signup</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
    <div class="signup-form">
        <h2>User Signup</h2>
        {% if error %}
            <p>Error: {{ error }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="first_name">First Name:</label>
                <input type="text" id="first_name" name="first_name" required>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" id="last_name" name="last_name" required>
            </div>
            <div class="form-group">
                <label for="gender">Gender:</label>
                <select id="gender" name="gender" required>
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="O">Other</option>
                </select>
            </div>
            <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" id="address" name="address" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="dob">Date of Birth:</label>
                <input type="date" id="dob" name="dob" required>
            </div>
            <div class="form-group">
                <label for="contact_no">Contact Number:</label>
                <input type="text" id="contact_no" name="contact_no" required>
            </div>
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="confirm_password">Confirm Password:</label>
                <input type="password" id="confirm_password" name="confirm_password" required>
            </div>
            <div class="form-group">
                <label for="account_type">Account Type:</label>
                <select id="account_type" name="account_type">
                    <option value="patient">Patient</option>
                    <option value="doctor">Doctor</option>
                </select>
            </div>
            <input type="submit" value="Next">
        </form>
    </div>
    <div class="additional-links">
        <p><a href="{% url 'home' %}">Back to Home</a></p>
    </div>
</body>
</html>


HMS/hospital/templates/update_doctor.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Doctor</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Edit Doctor</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes">
        <a href="{% url 'view_doctors' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/update_user.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit User</title>
    <link rel="stylesheet" href="{% static 'css/update_create.css' %}">
</head>
<body>
    <h1>Edit User</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes">
        <a href="{% url 'view_users' %}"><button type="button">Cancel</button></a>
    </form>
</body>
</html>

HMS/hospital/templates/view_admissions.html

{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admissions List</title>
    <link rel="stylesheet" href="{% static 'css/view_admissions.css' %}">
</head>
<body>
    <header>
        <h1>Admissions</h1>
    </header>
    
    <nav>
        <ul>
            <li><a href="{% url 'custom_admin_dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'edit_admin_profile' %}">Edit Admin Profile</a></li>
            <li><a href="{% url 'view_users' %}">Users</a></li>
            <li><a href="{% url 'view_patients' %}">Patients</a></li>
            <li><a href="{% url 'view_doctors' %}">Doctors</a></li>
            <li><a href="{% url 'view_admissions' %}">Admissions</a></li>
            <li><a href="{% url 'view_departments' %}">Departments</a></li>
            <li><a href="{% url 'view_wards' %}">Wards</a></li>
            <li><a href="{% url 'view_shifts' %}">Shifts</a></li>
            <li><a href="{% url 'view_beds' %}">Beds</a></li>
            <li><a href="{% url 'view_billings' %}">Billings</a></li>
            <li><a href="{% url 'view_discharged_patients' %}">Discharged Patients</a></li>
            <li><a href="{% url 'doctor_nurse_requests' %}">Doctor Requests</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </nav>
    <a href="{% url 'create_admission' %}">Admit Patient</a>
    <form method="GET">
        {{ form.as_p }}
        <button type="submit">Search/Filter</button>
        <a href="{% url 'view_admissions' %}?cancel_filter=True">Cancel Filter</a>
    </form>
    <table>
        <thead>
            <tr>
                <th>Admission ID</th>
                <th>Patient Username</th>
                <th>Name</th>
                <th>Ward Type</th>
                <th>Bed</th>
                <th>Admission Datetime</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for admission in admissions %}
            <tr>
                <td>{{ admission.id }}</td>
                <td>{{ admission.patient.user_profile.username }}</td>
                <td>{{ admission.patient.user_profile.full_name }}</td>
                <td>{{ admission.bed.ward.get_ward_type_display }}</td>
                <td>{{ admission.bed.bed_name }}</td>
                <td>{{ admission.admission_datetime }}</td>
                <td>
                    <a href="{% url 'edit_admission' admission.id %}">Edit</a>
                    <a href="{% url 'delete_admission' admission.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>



HMS/hospital/templates/view_beds.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Beds List</title>
    <link rel="stylesheet" href="{% static 'css/view_admissions.css' %}">
    <!-- Other necessary CSS links or stylesheets -->
</head>
<body>
    <header>
        <h1>Beds</h1>
    </header>
    
    <nav>
        <ul>
            <li><a href="{% url 'custom_admin_dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'edit_admin_profile' %}">Edit Admin Profile</a></li>
            <li><a href="{% url 'view_users' %}">Users</a></li>
            <li><a href="{% url 'view_patients' %}">Patients</a></li>
            <li><a href="{% url 'view_doctors' %}">Doctors</a></li>
            <li><a href="{% url 'view_admissions' %}">Admissions</a></li>
            <li><a href="{% url 'view_departments' %}">Departments</a></li>
            <li><a href="{% url 'view_wards' %}">Wards</a></li>
            <li><a href="{% url 'view_shifts' %}">Shifts</a></li>
            <li><a href="{% url 'view_beds' %}">Beds</a></li>
            <li><a href="{% url 'view_billings' %}">Billings</a></li>
            <li><a href="{% url 'view_discharged_patients' %}">Discharged Patients</a></li>
            <li><a href="{% url 'doctor_nurse_requests' %}">Doctor Requests</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </nav>
    <a href="{% url 'create_bed' %}">Create Bed</a>
    <form method="GET">
        {{ form.as_p }}
        <button type="submit">Search/Filter</button>
        <a href="{% url 'view_beds' %}?cancel_filter=True">Cancel Filter</a>
    </form>
    <table>
        <thead>
            <tr>
                <th>Bed</th>
                <th>Ward Type</th>
                <th>Admission ID</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for bed in beds %}
            <tr>
                <td>{{ bed.bed_name }}</td>
                <td>{{ bed.ward.get_ward_type_display}}</td>
                <td>{{ bed.admission.id }}</td>
                <td>
                    <a href="{% url 'edit_bed' bed.id %}">Edit</a>
                    <a href="{% url 'delete_bed' bed.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>



HMS/hospital/templates/view_users.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Users</title>
    <link rel="stylesheet" href="{% static 'css/view_admissions.css' %}">
</head>
<body>
    <header>
        <h1>Users</h1>
    </header>
    
    <nav>
        <ul>
            <li><a href="{% url 'custom_admin_dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'edit_admin_profile' %}">Edit Admin Profile</a></li>
            <li><a href="{% url 'view_users' %}">Users</a></li>
            <li><a href="{% url 'view_patients' %}">Patients</a></li>
            <li><a href="{% url 'view_doctors' %}">Doctors</a></li>
            <li><a href="{% url 'view_admissions' %}">Admissions</a></li>
            <li><a href="{% url 'view_departments' %}">Departments</a></li>
            <li><a href="{% url 'view_wards' %}">Wards</a></li>
            <li><a href="{% url 'view_shifts' %}">Shifts</a></li>
            <li><a href="{% url 'view_beds' %}">Beds</a></li>
            <li><a href="{% url 'view_billings' %}">Billings</a></li>
            <li><a href="{% url 'view_discharged_patients' %}">Discharged Patients</a></li>
            <li><a href="{% url 'doctor_nurse_requests' %}">Doctor Requests</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </nav>
    <a href="{% url 'create_user' %}">Create User</a>
    <form method="GET">
        {{ form.as_p }}
        <button type="submit">Search/Filter</button>
        <a href="{% url 'view_users' %}?cancel_filter=True">Cancel Filter</a>
    </form>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Name</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Contact Number</th>
                <th>Account Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            
            {% for user in all_users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.get_gender_display }}</td>
                    <td>0{{ user.contact_no }}</td>
                    <td>{{ user.get_account_type_display }}</td>
                    <td>
                        <a href="{% url 'edit_user' user.id %}">Edit</a>
                        <a href="{% url 'delete_user' user.id %}">Delete</a>
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>